**1**

In [1]:
import pandas as pd

df = pd.DataFrame({
    'Category': ['Apple', 'Banana', 'Apple', 'Orange', 'Banana', 'Apple'],
    'Value': [10, 20, 30, 40, 50, 60]
})

print("Before optimization:")
print(df.dtypes)

df['Category'] = df['Category'].astype('category')

print("\nAfter optimization:")
print(df.dtypes)

Before optimization:
Category    object
Value        int64
dtype: object

After optimization:
Category    category
Value          int64
dtype: object

2

In [2]:
import pandas as pd

df = pd.DataFrame({'Value': [10, 20, 30, 40, 50]})

df['Double_Value'] = df['Value'] * 2

print(df)

   Value  Double_Value
0     10            20
1     20            40
2     30            60
3     40            80
4     50           100

3

In [3]:
import pandas as pd

df = pd.DataFrame({'Value': [10, 20, 30, 40, 50]})

df.eval('Triple_Value = Value * 3', inplace=True)

print(df)

   Value  Triple_Value
0     10            30
1     20            60
2     30            90
3     40           120
4     50           150

4

In [4]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40]
})

filtered_df = df.query('Age > 30')

print(filtered_df)

      Name  Age
2  Charlie   35
3    David   40

5

In [5]:
import pandas as pd

arrays = [
    ['USA', 'USA', 'Canada', 'Canada'],
    ['East', 'West', 'East', 'West']
]

index = pd.MultiIndex.from_arrays(arrays, names=('Country', 'Region'))

df = pd.DataFrame({'Sales': [100, 150, 200, 250]}, index=index)

print(df.loc[('Canada', 'East')])

Sales    200
Name: (Canada, East), dtype: int64

6

In [6]:
import pandas as pd

df = pd.DataFrame({
    'Department': ['HR', 'HR', 'IT', 'IT'],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Salary': [50000, 52000, 70000, 68000]
})

pivot_df = df.pivot_table(values='Salary', index='Department', columns='Gender', aggfunc='mean')

print(pivot_df)

Gender       Female     Male
Department
HR          52000.0  50000.0
IT          68000.0  70000.0

7

In [7]:
import pandas as pd

df = pd.DataFrame({
    'Values': [10, 20, 30, 40, 50]
})

df['Rolling_Mean'] = df['Values'].rolling(window=2).mean()

print(df)

   Values  Rolling_Mean
0      10           NaN
1      20          15.0
2      30          25.0
3      40          35.0
4      50          45.0